### PR TITLE
Rhino3dmio linux native support

### PR DESCRIPTION
**Pull request by arendvw**
- Added a hacked makefile from opennurbs to include the 3dmio-toolkit
  ccp files
- Added linux toggles to rhcommon_c_api.h (Mostly copied from the
  android part of the file)
- Renamed StdAfx.h (errors occurred because of case-sensitive issues)
- Modified the build_native.py to include linux.

Here are some things that I think need review:

I just noticed a small error in **build_native.py**: the first line contains a space, this should not have been comitted.

**For the Makefile:**
I've built the seperate ccp files as shared objects, although I'm not quite sure if this is the right or wrong approach, or if it even matters at all. (Line 38 of the Makefile)

Possibly more files are being compiled then necessary. I've taken all of the opennurbs files, and added the ones listed in the android makefile.

### CODE REVIEW

**Comment by sbaer** [comment]
Thanks, we may not be able to review and include this PR in the near future, but we will keep it open until one of us can review it. Everyone is just busy with other tasks at the moment.

**Comment by dbelcher** [comment]
Nice!  I want to take a closer look and test this as soon I can.

**Comment by arendvw** [comment]
Great! As a reference, the process of changes and a short tutorial for this pull request is posted here  [in the discourse forum](http://discourse.mcneel.com/t/compiling-the-3dmiotoolkit-under-linux/32271)

**Comment by arendvw** [comment]
This is solved in a different matter now

**Comment by maxsu** [comment]
Link to the solution?

**Comment by arendvw** [comment]
> Link to the solution?
> […](#)
A solution was added by @sbaer for building under linux, in the new [Rhino3DM repository](https://github.com/mcneel/rhino3dm) and is discussed on [this thread](https://discourse.mcneel.com/t/rhino3dm-net-source-available/85003/10) of the McNeel Discourse forum.

**Pull request closed without merging**
